title: MHTIP Project
author: Ethan Nelson
#email: 
description: > 
  This site is home to the 
  Meridional Heat Transport Intercomparison Project, aimed
  at documenting, understanding, and improving the transport
  of heat in the Earth system meridionally. Data, methods,
  and images are available to replicate our analysis.

# social links
github_username:  mhtip/

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - datasets/index.md
 - quicklook/index.md

# Build settings
markdown: kramdown

collections:
  datasets:
    output: true
